#
###################################
# Site wide configuration
####################################
#
title: Myths.xyz
email:
description: All the free myths you can handle.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url:

#
###################################
# Jekyll configuration
####################################
#
defaults:
  -
    scope:
      path: ""
      type: "books"
    values:
      layout: "post"

collections:
  books:
    output: true

markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->
encoding: Windows-1252

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Myths.xyz
  avatar: 
  job: "Greek and Roman Mythology"
  bio: "All the best mythology under one roof."
  email:
  disqus-shortname:
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
